import { Inter } from 'next/font/google'
import '../public/template/css/sb-admin-2.min.css'
import '../public/template/css/fontawesome-free/css/all.min.css'
import '../public/template/css/bootstrap.min.css'
import './globals.css'
import { UserProvider } from './context/userContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </UserProvider>

  )
}
